name: Run `just` (build + test)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    just-everything:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: ATiltedTree/setup-rust@v1
              with:
                  rust-version: stable
            - uses: extractions/setup-just@v1
            - uses: oven-sh/setup-bun@v1
            - name: Install deps
              run: cd web && bun i && cd ..
            - name: Build
              run: just build
            - name: Test
              run: just test
